version: '3'
services:
  ecemfe-app:
    image: ecemnurnaz/ecemfe-app:2.3
    ports:
      -8082:8082
  ecems-app:
    image: ecemnurnaz/ecems-app:1.1
    ports:
      - 8080:8080
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: 
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes: 
  mongo-data:
    driver: local
    