version: '3'
services:
  mongodb:
    image: mongo:5.0.3
    restart: always
    ports:
      - 27017:27017     
  sringboot-mongodb:
    image: springboot-mongodb
    container_name: "mongo-container"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:  
      - spring.data.mongodb.host=host.docker.internal
    depends_on:
      - mongodb
